apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: first-commit-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: first-commit.hackathon.sev-2.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80